# This workflow will install Deno then run Deno lint and test.

name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DENO_DIR: deno_dir
      PUPPETEER_DOWNLOAD_PATH: deno_dir/deno_puppeteer/chromium/
      PUPPETEER_CHROMIUM_REVISION: 991974

    steps:
      - name: Echo token
        run: echo ${GITHUB_TOKEN:0:4}
